reference.Lab
reference.User
reference.Project

subject.Species
subject.Source
subject.Strain
subject.Sequence
subject.Allele
subject.AlleleSequence
subject.Line
subject.LineAllele
subject.Subject
subject.BreedingPair
subject.Litter
subject.LitterSubject
subject.SubjectProject
subject.Weaning
subject.Death
subject.GenotypeTest
subject.Zygosity